name: Python Linting and Formatting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Chekout repository
        uses: actions/checkout@v2
        
        name: Set up Python
        uses: actions/setup-python@v2
        
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirments.txt

      - name: Run flake8
        run: |
          flake8 .

      - name: Run black
        run: |
          black --check .